version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - chat-app-postgres:/var/lib/postgresql/data

volumes:
  chat-app-postgres:
